# Specifies the GHC version and set of packages available
resolver: lts-13.11

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- git: https://github.com/haskell-distributed/distributed-process.git
  commit: 660d554f6acd2dba8b605c84e8fa69e45708bc14
- git: https://github.com/adjoint-io/distributed-process-systest.git
  commit: 78770663c8b5309522db27dd290de5aee07c5366
- git: https://github.com/adjoint-io/network-transport-tcp.git
  commit: fda9660e55d22cb8c406331483605db057b08c0e
- rematch-0.2.0.0
- exceptions-0.10.0
- distributed-static-0.3.9

# Override default flag values for local packages and extra-deps
flags: {}
